// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM8TYHGb-rLGofur-oz53CnReRQP--S7c',
    appId: '1:697326457207:web:be965e4db06d65f73b9172',
    messagingSenderId: '697326457207',
    projectId: 'chat-app-fb4e7',
    authDomain: 'chat-app-fb4e7.firebaseapp.com',
    storageBucket: 'chat-app-fb4e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG1ZHpq_vSHd4YAEQaznhjGT1Hu2yawXU',
    appId: '1:697326457207:android:cacf9c96d1bcb9623b9172',
    messagingSenderId: '697326457207',
    projectId: 'chat-app-fb4e7',
    storageBucket: 'chat-app-fb4e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo2-4S6QCTYA48fkbZFUtWb3kODFHO6hw',
    appId: '1:697326457207:ios:62616afcff68f3d13b9172',
    messagingSenderId: '697326457207',
    projectId: 'chat-app-fb4e7',
    storageBucket: 'chat-app-fb4e7.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo2-4S6QCTYA48fkbZFUtWb3kODFHO6hw',
    appId: '1:697326457207:ios:62616afcff68f3d13b9172',
    messagingSenderId: '697326457207',
    projectId: 'chat-app-fb4e7',
    storageBucket: 'chat-app-fb4e7.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM8TYHGb-rLGofur-oz53CnReRQP--S7c',
    appId: '1:697326457207:web:d056c305d6208ce43b9172',
    messagingSenderId: '697326457207',
    projectId: 'chat-app-fb4e7',
    authDomain: 'chat-app-fb4e7.firebaseapp.com',
    storageBucket: 'chat-app-fb4e7.appspot.com',
  );
}
